- name: Checkout testes
  uses: actions/checkout@v3

- name: Clone API
  run: git clone https://github.com/bellacarmobrito/api-entregas-aula-testes-automatizados.git

- name: Build API JAR
  run: |
    cd api-entregas-aula-testes-automatizados
    ./mvnw clean package -DskipTests

- name: Start API
  run: |
    cd api-entregas-aula-testes-automatizados
    docker compose up -d --build

- name: Wait for API
  run: sleep 15

- name: Run tests
  run: ./mvnw test